version: '3'

services:
  web:
    volumes:
      - .:/shapes-test
    ports:
      - 8081:80
    env_file:
      - .env
    entrypoint: ["/shapes-test/docker/web_entrypoint.sh"]
    environment:
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
      - PYTHONUNBUFFERED=${PYTHONUNBUFFERED}
      - FIREBASE_CREDENTIALS=${FIREBASE_CREDENTIALS}
      - GS_CREDENTIALS=${GS_CREDENTIALS}
    build: .
    links:
      - redis:redis
    networks:
      - shapes-test-network

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=shapes_test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=shapes-test
    ports:
      - "5432:5432"
  unittest:
    volumes:
      - .:/shapes-test
    depends_on:
      - db
    entrypoint: [ "/shapes-test/docker/unit_test_entrypoint.sh" ]
    environment:
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
      - DB_HOST=db
      - DB_PORT=5432
    build: .

  redis:
    image: "redis:alpine"
    command: redis-server
    ports:
      - "6380:6379"
    networks:
      - shapes-test-network

networks:
  shapes-test-network:
    driver: bridge
