# Generated by Django 3.2.4 on 2021-10-20 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shape', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shape',
            name='type',
            field=models.CharField(choices=[('Square', 'Square'), ('Rectangle', 'Rectangle'), ('Triangle', 'Triangle')], max_length=32),
        ),
    ]
